micronaut:
  application:
    name: keymanagerRest
  server:
    port: ${SERVER_PORT:8080}

jackson:
  serialization:
    writeDatesAsTimestamps: false

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  server:
    host: localhost
    port: 8182
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'